 
# use cpu for easy debug
device: cuda
seed: 42
batch_size: 64
limit_example_length: 100000
# lm context size is equal max_seq_length
max_seq_length: 15
# must be even, and >= 2
max_context_size: 6
min_seq_length: 1
temperature: 0.7
top_k: 0
top_p: 0.9
no_sample: False

pretrained_fname: models/model__epoch1/model.pt
data_path: datas/
cache_path: caches/

 
