
# use cpu for easy debug
device: cuda
seed: 42
n_epochs: 10
n_epochs_early_stage: 0
clip_grad: 1
# batch_size: 128
batch_size: 128
limit_example_length: 
# most weibo are short 
max_seq_length: 15
shuffle_data: True
# pretrain_emb must include special_tokens?
# english letter will removed in max_vocab_size by gensim
max_vocab_size: 42000
pretrain_emb: True

emb_freeze: True
enc_dropout: 0.1
dec_dropout: 0.1

# lr: 1.5e-4
lr: 0.05
weight_decay: 0.99

model_path: models/
pretrained_path:
data_path: tmp/
# data_path: datas/
cache_path: caches/
corpus_fname:
vec_fname: models/vec-512a.txt
vocab_fname: models/vocab-512a.txt

max_context_size: 6
num_layers: 6
n_head: 8
# n_head: 5
d_model: 512
# d_model: 100
d_ff: 2048
attn_alpha: 1
